-- MySQL Script generated by MySQL Workbench
-- Sat Nov 14 06:46:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_parcial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_parcial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_parcial` DEFAULT CHARACTER SET utf8 ;
USE `db_parcial` ;

-- -----------------------------------------------------
-- Table `db_parcial`.`Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_parcial`.`Libro` (
  `IdLibro` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(50) NOT NULL,
  `Editorial` VARCHAR(50) NOT NULL,
  `Area` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IdLibro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_parcial`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_parcial`.`Autor` (
  `IdAutor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Apellido` VARCHAR(40) NOT NULL,
  `Nacionalidad` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`IdAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_parcial`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_parcial`.`Estudiante` (
  `IdLector` INT NOT NULL AUTO_INCREMENT,
  `CI` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Apellido` VARCHAR(40) NOT NULL,
  `Direccion` VARCHAR(60) NOT NULL,
  `Carrera` VARCHAR(40) NOT NULL,
  `Fecha_nac` DATE NOT NULL,
  PRIMARY KEY (`IdLector`),
  UNIQUE INDEX `CI_UNIQUE` (`CI` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_parcial`.`LibAut`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_parcial`.`LibAut` (
  `IdAutor` INT NOT NULL,
  `IdLibro` INT NOT NULL,
  INDEX `Lib_fk_idx` (`IdLibro` ASC) VISIBLE,
  PRIMARY KEY (`IdAutor`, `IdLibro`),
  CONSTRAINT `lib_fk`
    FOREIGN KEY (`IdLibro`)
    REFERENCES `db_parcial`.`Libro` (`IdLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `aut_fk`
    FOREIGN KEY (`IdAutor`)
    REFERENCES `db_parcial`.`Autor` (`IdAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_parcial`.`Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_parcial`.`Prestamo` (
  `IdLector` INT NOT NULL,
  `IdLibro` INT NOT NULL,
  `FechaPrestamo` DATE NOT NULL,
  `Devuelto` TINYINT NOT NULL DEFAULT 0,
  INDEX `lib_fk_idx` (`IdLibro` ASC) VISIBLE,
  PRIMARY KEY (`IdLector`, `IdLibro`),
  CONSTRAINT `libr_fk`
    FOREIGN KEY (`IdLibro`)
    REFERENCES `db_parcial`.`Libro` (`IdLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lec_fk`
    FOREIGN KEY (`IdLector`)
    REFERENCES `db_parcial`.`Estudiante` (`IdLector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
